"""Machine-readable handoff from the rankings publisher to Editorial Desk."""

from __future__ import annotations

import json
from pathlib import Path

from .models import LeagueConfig, RankingResult


PUBLICATION_KEYS = {
    "main": "ironbound_weekly",
    "free": "unbound_weekly",
}


def build_editorial_handoff(
    config: LeagueConfig,
    result: RankingResult,
) -> dict:
    publication_key = PUBLICATION_KEYS.get(config.key)
    if publication_key is None:
        raise ValueError(f"No Editorial Desk publication mapping for {config.key!r}")

    rankings = []
    playoff_odds = []
    for team in result.teams:
        rankings.append(
            {
                "roster_id": team.roster_id,
                "team": team.team_name,
                "rank": team.rank,
                "previous_rank": team.previous_rank,
                "movement": team.movement,
                "score": team.score,
            }
        )
        playoff_odds.append(
            {
                "roster_id": team.roster_id,
                "team": team.team_name,
                "projected_record": team.projected_record,
                "playoff": team.make_playoffs_pct,
                "division": team.win_division_pct,
                "bye": team.first_round_bye_pct,
                "final": team.make_final_pct,
                "championship": team.win_championship_pct,
            }
        )

    return {
        "schema_version": 1,
        "publication_key": publication_key,
        "source_metadata": {
            "producer": "Ironbound_power_ranks",
            "league_key": config.key,
            "league_id": result.league.league_id,
            "season": result.league.season,
            "week": result.league.week,
            "generated_at": result.generated_at,
            "forecast_simulations": result.forecast_simulations,
            "forecast_model": result.forecast_model,
            "dynasty_sources": list(result.dynasty_sources),
            "lineup_sources": list(result.lineup_sources),
        },
        "official_power_rankings": rankings,
        "playoff_odds": playoff_odds,
        "notes": [
            "Power Rankings and playoff odds were generated by Ironbound_power_ranks.",
            "Weekly player usage is generated internally by Editorial Desk from nflverse data.",
            "WAR and cWAR are optional analytical enrichment and are not required for weekly publication.",
        ],
    }


def write_editorial_handoff(
    config: LeagueConfig,
    result: RankingResult,
    output: Path,
) -> Path:
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = build_editorial_handoff(config, result)
    output.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return output
