"""Machine-readable handoff from the rankings publisher to Editorial Desk."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
import shutil

from .models import LeagueConfig, RankingResult


PUBLICATION_KEYS = {
    "main": "ironbound_weekly",
    "free": "unbound_weekly",
}


def build_editorial_handoff(
    config: LeagueConfig,
    result: RankingResult,
    *,
    publication_assets: dict | None = None,
) -> dict:
    publication_key = PUBLICATION_KEYS.get(config.key)
    if publication_key is None:
        raise ValueError(f"No Editorial Desk publication mapping for {config.key!r}")

    rankings = []
    playoff_odds = []
    for team in result.teams:
        rankings.append(
            {
                "roster_id": team.roster_id,
                "team": team.team_name,
                "rank": team.rank,
                "previous_rank": team.previous_rank,
                "movement": team.movement,
                "score": team.score,
            }
        )
        playoff_odds.append(
            {
                "roster_id": team.roster_id,
                "team": team.team_name,
                "projected_record": team.projected_record,
                "playoff": team.make_playoffs_pct,
                "division": team.win_division_pct,
                "bye": team.first_round_bye_pct,
                "final": team.make_final_pct,
                "championship": team.win_championship_pct,
            }
        )

    return {
        "schema_version": 1,
        "publication_key": publication_key,
        "source_metadata": {
            "producer": "Ironbound_power_ranks",
            "league_key": config.key,
            "league_id": result.league.league_id,
            "season": result.league.season,
            "ranking_week": result.league.week,
            "results_through_week": max(0, int(result.league.week) - 1),
            "generated_at": result.generated_at,
            "forecast_simulations": result.forecast_simulations,
            "forecast_model": result.forecast_model,
            "dynasty_sources": list(result.dynasty_sources),
            "lineup_sources": list(result.lineup_sources),
        },
        "official_power_rankings": rankings,
        "playoff_odds": playoff_odds,
        "publication_assets": dict(publication_assets or {}),
        "notes": [
            "Power Rankings and playoff odds were generated by Ironbound_power_ranks.",
            "Weekly player usage is generated internally by Editorial Desk from nflverse data.",
            "WAR and cWAR are optional analytical enrichment and are not required for weekly publication.",
        ],
    }


def write_editorial_handoff(
    config: LeagueConfig,
    result: RankingResult,
    output: Path,
    *,
    power_rankings_image: Path | None = None,
    playoff_forecast_image: Path | None = None,
) -> Path:
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)

    assets: dict[str, dict] = {}
    for key, source, suffix in (
        ("power_rankings", power_rankings_image, "power-rankings"),
        ("playoff_forecast", playoff_forecast_image, "playoff-forecast"),
    ):
        if source is None:
            continue
        source = Path(source)
        if not source.is_file():
            raise FileNotFoundError(f"Publication asset not found: {source}")
        publication_key = PUBLICATION_KEYS[config.key]
        filename = f"{publication_key}-{suffix}.png"
        asset_dir = output.parent / "assets"
        asset_dir.mkdir(parents=True, exist_ok=True)
        destination = asset_dir / filename
        shutil.copyfile(source, destination)
        digest = hashlib.sha256(destination.read_bytes()).hexdigest()
        assets[key] = {
            "filename": filename,
            "repo_path": f"handoff/assets/{filename}",
            "media_type": "image/png",
            "sha256": digest,
            "bytes": destination.stat().st_size,
            "generated_at": result.generated_at,
            "owner": "Ironbound_power_ranks",
            "placement_policy": "use supplied graphic unchanged",
        }

    payload = build_editorial_handoff(
        config,
        result,
        publication_assets=assets,
    )
    output.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return output
